### ISSUE TITLE
Add possibility to have sortable_tree view be closed and opened

### ISSUE THREAD

**Issue by mobilutz** [the-teacher/the_sortable_tree#78]
For a project it would be great to have the sortable tree be closed and opened.

We implemented it with a little hack but now we need to change the jquery UI nested sortable file. You know this is not good, so I am wondering if the functionality could be added to the_sortable_tree

**Comment by the-teacher** [comment]
@mobilutz  Hello! 
as you know `jquery UI nested sortable` file is external dependency and I want not touch or change it, because it can be impossible to support changes. For now gem is freezed, because all my tasks finished and I haven't time to improve it. Sorry. Moreover gem current version of gem works fine for my projects in production, and I haven't reasons come back to this code.

For now best way to get required feature is fork gem and make you own changes. Sorry for that, but is the only way to get required feature.

Thank you for your feedback and trust to my code!
