### ISSUE TITLE
Wrong rendering when IDs of tree not in order

### ISSUE THREAD

**Issue by patrick-nits** [the-teacher/the_sortable_tree#84]
Considering the following setup, the TheSortableTreeHelper#build_server_tree is rendering nodes in wrong order.

**Baseline**

Node#1
|     Node#5
|     |      Node#2
|     |      |      Node#3
|     |      |      |      Node#4

Where `#X` defines the `id` of the Node.  

When trying to render the subtree (Node#2; Node#3; Node#4), `TheSortableTreeHelper#113` tries to determine the roots to be rendered by selecting the Node with the **smallest** `parent_id`.
In this case Node#3 would be selected as root node.

- Node#2 --> root: Node#5
- **Node#3 --> root: Node#2**
- Node#4 --> root: Node#3

**Comment by patrick-nits** [comment]
Fix and Description in #85

**Comment by the-teacher** [comment]
@patrick-nits hello! Thanks for the good catch!
Your explanation of the problem is very good, but it's difficult to me to understand algorithm which you use to find right parent node.
I will try to understand it in few nearest days when I will have dome free time.
If you can provide any kind of test for this case it will be amazing. If not, please, give me some time to analyze and understand how your patch works.
Thanks a lot for your help!

**Comment by patrick-nits** [comment]
Considering `Node#1` <-- `Node#5` <-- `Node#2` <-- `Node#3` <-- `Node#4` and trying to render `Node#2,3,4`.

Then `opts[:boost] = {5 => Node#2, 2 => Node#3, 3 => Node#4}` 
In short, `parent_ids = [2,3,5]` and `node_ids = [2,3,4]`.
Combining `parent_ids` and `node_ids`with **XoR** results in `[5,4]` which are either leaf or root (for a tree or subtree). **The XoR is the critical part here.**

Using the candidates `[5,4]`, the algorithm then checks if there is a node whos parent is one of the candidate its, which in this case is `Node#2`. This will then be the root for the subtree to be rendered.

**Comment by the-teacher** [comment]
@patrick-nits sorry, was too busy this weekend. I plan to check it today and I will merge and release if my main app, where I user this gem will work fine.
Thanks again!
